[4.3.4]
# initial update to configure sprites and metrics
http://drive.google.com/uc?export=download&id=0B4Pi8i4pFhL-Y2k1ZkxtblN4TG8,_installer/bin/internals.dat
http://drive.google.com/uc?export=download&id=0B4Pi8i4pFhL-WlZndDdUTWhQUDA,_installer/bin/metrics.dat
http://drive.google.com/uc?export=download&id=0B4Pi8i4pFhL-X0tGbG9wc2tLWDQ,execute
http://drive.google.com/uc?export=download&id=0B4Pi8i4pFhL-ajVrUnRxQXNVVG8,execute
[4.3.5]
# positioner fix
http://drive.google.com/uc?export=download&id=0B4Pi8i4pFhL-dGhXZ2xYTXVJcjQ,Data/PositionerScripts.rxdata
http://drive.google.com/uc?export=download&id=0B4Pi8i4pFhL-c01MV1I2dFJGazA,EliteBattle_0
[4.3.6]
# S&M VS sequence rework
# actually I broke this thing
http://drive.google.com/uc?export=download&id=0B4Pi8i4pFhL-c01MV1I2dFJGazA,EliteBattle_0
http://drive.google.com/uc?export=download&id=0B4Pi8i4pFhL-NG4xX0ZudHF1MWM,EliteBattle_1
http://drive.google.com/uc?export=download&id=0B4Pi8i4pFhL-SGJpeV9ZNE1VZDA,EliteBattle_2
http://drive.google.com/uc?export=download&id=0B4Pi8i4pFhL-OHNhRVltMzVyRU0,EliteBattle_5
http://drive.google.com/uc?export=download&id=0B4Pi8i4pFhL-YUZjRXN3eUVsMjA,EliteBattle_6
[4.4.0]
# more S&M VS sequences
http://drive.google.com/uc?export=download&id=0B4Pi8i4pFhL-c01MV1I2dFJGazA,EliteBattle_0
http://drive.google.com/uc?export=download&id=0B4Pi8i4pFhL-NG4xX0ZudHF1MWM,EliteBattle_1
http://drive.google.com/uc?export=download&id=0B4Pi8i4pFhL-SGJpeV9ZNE1VZDA,EliteBattle_2
http://drive.google.com/uc?export=download&id=0B4Pi8i4pFhL-WHp3eC1ib0JlUkU,EliteBattle_3
http://drive.google.com/uc?export=download&id=0B4Pi8i4pFhL-OHNhRVltMzVyRU0,EliteBattle_5
http://drive.google.com/uc?export=download&id=0B4Pi8i4pFhL-YUZjRXN3eUVsMjA,EliteBattle_6
http://drive.google.com/uc?export=download&id=10tUD0DwEi9Zq7nY-o2xlWBJSOljnZOaL,pack
[4.4.1]
# forgot to add the whole Graphics/Pictures folder
http://drive.google.com/uc?export=download&id=1J57LVdhzzgixdD-wi-CKuE0kBu-5Cskk,pack
[4.4.2]
# fixes the S&M styled VS Species animation
http://drive.google.com/uc?export=download&id=0B4Pi8i4pFhL-YUZjRXN3eUVsMjA,EliteBattle_6